[project]
name = "sales-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "auto-py-to-exe>=2.48.1",
    "dotenv>=0.9.9",
    "pip>=25.2",
    "pydantic>=2.11.7",
]
